name: Mirror to Personal Repo

on:
  push:
    branches:
      - '**'  # Mirror all branches

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.name "McShnaib"
          git config --global user.email "shaheen.mcshnaib@gmail.com"

      - name: Add personal remote
        run: |
          git remote add mirror https://McShnaib:${{ secrets.PERSONAL_GH_PAT }}@github.com/McShnaib/shaheen-waitlist-mirror.git
          git push --mirror mirror
